trainer:
  logger: true
  enable_checkpointing: true
  max_epochs: 250
  log_every_n_steps: 5
  gradient_clip_val: 0.5
  accelerator: cuda
  devices:  1
  precision: 32

model:
  class_path: model.Model
  dict_kwargs:
    input_channels: 5
    encoder_channels: [32, 64, 128, 256]
    decoder_channels: [256, 128, 64, 32]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 1]
    dropout: 0.1
    activation: 'ReLU'
    latent_dim: 10
    layers: 3
    beta: 1.
    lambdas: [1.0, 1.0, 1.0]
    triggers:
      VAE:
        lr: 1e-5
        weight_decay: 1e-6
    optimizer: 'adam'

data:
  class_path: data.DataModule
  init_args:
    batch_size: 4
    num_workers: 8
    pin_memory: true
