trainer:
  logger: true
  enable_checkpointing: true
  max_epochs: 50
  accelerator: cuda
  devices:  1
  precision: 32

model:
  class_path: model.Model
  dict_kwargs:
    input_channels: 5
    encoder_channels: [32, 64, 128]
    decoder_channels: [128, 64, 32]
    kernel_sizes: [3, 3, 3]
    strides: [2, 2, 2]
    paddings: [1, 1, 1]
    dropout: 0.1
    activation: 'Tanh'
    latent_dim: 20
    beta: 0.05
    lambdas: [0.1, 1.0, 1.0]
    triggers:
      VAE:
        lr: 1e-4
        weight_decay: 1e-5
    optimizer: 'adam'

data:
  class_path: data.DataModule
  init_args:
    batch_size: 32
    num_workers: 8
    pin_memory: true
