trainer:
  logger: true
  enable_checkpointing: true
  max_epochs: 250
  accelerator: cuda
  devices:  1
  precision: 32

model:
  class_path: cnn1d.model.Model
  dict_kwargs:
    # TODO

data:
  class_path: data.DataModule
  init_args:
    batch_size: 32
    num_workers: 8
    pin_memory: true
